<h1><?php echo $this->title; ?></h1>

<?php if(isset($this->messages)): ?>
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
        <?php echo $this->htmlList($this->messages, false, array('class' => 'text-warning')); ?>
    </div>
<?php endif; ?>

<?php echo $this->partial('market/partials/item', array('listing' => $this->listing)); ?>